Repository Arquisoft/dede_en3b, pull requests merged in 2022-03, with the labels that each got.

#40 DB has been created, added file to create the schema
  db/schema.js
  db/schema.ts
  package-lock.json
  package.json
Labels: enhancement, database📕

#41 UX - Main Window v1 + IProduct + ProductComponent + NavigationBar + css
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/IProduct.tsx
  webapp/src/components/NavigationBar.tsx
  webapp/src/components/ProductComponent.tsx
  webapp/src/index.tsx
Labels: frontend

#39 Solid facade first iteration done
  README.md
  README_es.md
  docker-compose.yml
  restapi/Dockerfile
  restapi/README.md
  restapi/README_es.md
  restapi/api.ts
  restapi/monitoring/grafana/provisioning/dashboards/dashboard.yml
  restapi/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  restapi/monitoring/grafana/provisioning/datasources/datasource.yml
  restapi/monitoring/prometheus/prometheus.yml
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tsconfig.json
  webapp/.dockerignore
  webapp/Dockerfile
  webapp/README.md
  webapp/README_es.md
  webapp/e2e/features/register-form.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/jest.config.ts
  webapp/loadtestexample/GetUsersList.scala
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/public/manifest.json
  webapp/public/robots.txt
  webapp/server.ts
  webapp/src/App.css
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/SOLID/API.ts
  webapp/src/api/api.ts
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/index.css
  webapp/src/index.tsx
  webapp/src/react-app-env.d.ts
  webapp/src/reportWebVitals.ts
  webapp/src/setupTests.ts
  webapp/src/shared/shareddtypes.ts
  webapp/tsconfig.json
Labels: enhancement, solid 🪨

#58 Diagrama 6.1 revisado
  docs/06_runtime_view.adoc
  docs/images/06-01_Nico_SequenceDiagram.png
  docs/images/61SequenceDiagram.png
Labels: documentation, enhancement

#60 there was another typo in the name :D
  docs/06_runtime_view.adoc
Labels: documentation, fix needed ⚒️

#62 Now it should be all fixed
  webapp/src/SOLID/API.ts
Labels: bug, solid 🪨

#63 Fixing a bit of stuff
  restapi/api.ts
Labels: database📕, fix needed ⚒️

#65 Fixed even more errors even if it was not neccesary
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/SOLID/API.ts
Labels: bug, solid 🪨

#64 Added the filter for the products shown
  restapi/api.ts
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/SOLID/API.ts
  webapp/src/api/api.ts
  webapp/tsconfig.json
Labels: enhancement, frontend

#68 Some changes got removed from main god knows how
  webapp/src/SOLID/API.ts
Labels: solid 🪨

#67 Section 5 fixed
  docs/images/05_building_blocks_overview.png
Labels: documentation

#70 Celia y Oscar: shopping cart, connection to the pod and individual project view
  package-lock.json
  package.json
  restapi/model/Products.ts
  restapi/package-lock.json
  restapi/package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/CartItem.styles.ts
  webapp/src/components/CartItem.tsx
  webapp/src/components/ICartItem.tsx
  webapp/src/components/IProduct.tsx
  webapp/src/components/LoginComponent.tsx
  webapp/src/components/NavigationBar.tsx
  webapp/src/components/ProductComponent.tsx
  webapp/src/components/ProductList.tsx
  webapp/src/index.tsx
  webapp/src/routes/Cart.styles.ts
  webapp/src/routes/Cart.tsx
  webapp/src/routes/Catalogue.tsx
  webapp/src/routes/IndividualProduct.tsx
  webapp/src/routes/Product.styles.ts
Labels: frontend

#72 Fix of section 4
  docs/04_solution_strategy.adoc
Labels: documentation

#73 Section 11 of documentation added
  docs/11_technical_risks.adoc
Labels: documentation

#76 Nico enh 66 view orders
  restapi/api.ts
  restapi/model/Order.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/routes/Cart.tsx
Labels: database📕

#74 Section 7 of the documentation finished.
  docs/07_deployment_view.adoc
  docs/images/07-Deployment-View-Development-En.png
  docs/images/07-Deployment-View-En.png
Labels: documentation

#80 Section 11 and 3 fixed for correct deployment
  docs/03_system_scope_and_context.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#81 Oscar 71: Documentation section 10
  docs/10_quality_scenarios.adoc
  docs/images/10_Oscar_QualityTree.png
Labels: documentation

#77 Nico doc 55 section8v1
  docs/08_concepts.adoc
  docs/images/08-01_Nico_DomainModel.png
Labels: documentation

#84 All fixed, all deployed.
  docs/03_system_scope_and_context.adoc
Labels: documentation, enhancement

#85 Section 9 done
  docs/09_design_decisions.adoc
Labels: documentation, enhancement

#106 Home view created
  webapp/src/App.tsx
  webapp/src/components/NavigationBar.tsx
  webapp/src/routes/Home.tsx
  webapp/src/static/images/buttons/orders.png
  webapp/src/static/images/buttons/shop.png
Labels: ux 🪟, frontend 🧱

#107 Jesus enh 90 session
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/routes/Cart.tsx
Labels: enhancement

#111 Tests for the products part of the RESTApi
  restapi/api.ts
  restapi/model/Products.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/tests/api.test.ts
  restapi/tests/test.server.ts
  webapp/src/App.tsx
  webapp/src/routes/Cart.tsx
Labels: backend 💾, test 🧪
