Repository Arquisoft/dede_en3b, pull requests merged in 2022-04, with the labels that each got.

#119 Beginning tests of the webapp, configuration and home page tests
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/routes/Home.tsx
  webapp/src/setupTests.ts
  webapp/src/tests/App.test.tsx
  webapp/src/tests/home.test.tsx
  webapp/tsconfig.json
Labels: test 🧪

#127 Tests for home view and navigation bar created
  webapp/src/components/NavigationBar.tsx
  webapp/src/routes/Home.tsx
  webapp/src/tests/App.test.tsx
  webapp/src/tests/NavigationBar.test.tsx
  webapp/src/tests/home.test.tsx
Labels: test 🧪

#131 Merge pull request from fork
  webapp/src/routes/Cart.tsx
Labels: heroku 🤺, docker 🐳

#144 The CI works now
  .github/workflows/asw2122.yml
  restapi/package-lock.json
  restapi/package.json
  webapp/src/api/ShippingApi.ts
  webapp/src/api/api.ts
  webapp/src/components/AddPaymentMeanComponent.tsx
  webapp/src/components/ConfirmationComponent.tsx
  webapp/src/components/OrderItemProduct.tsx
  webapp/src/routes/Home.tsx
Labels: bug, heroku 🤺, docker 🐳

#146 Added tests for shopping cart and products views
  webapp/src/components/NavigationBar.tsx
  webapp/src/routes/IndividualProduct.tsx
  webapp/src/tests/App.test.tsx
  webapp/src/tests/Catalogue.test.tsx
  webapp/src/tests/IndividualProduct.test.tsx
  webapp/src/tests/NavigationBar.test.tsx
  webapp/src/tests/ShoppingCart.test.tsx
Labels: test 🧪

#148 Some more fixes
  restapi/server.ts
  restapi/solid.ts
  webapp/src/api/api.ts
Labels: heroku 🤺, docker 🐳

#149 Commented some lines to ensure that CI works
  webapp/src/App.tsx
  webapp/src/components/AddPaymentMeanComponent.tsx
Labels: heroku 🤺, docker 🐳

#150 Perhaps this fixes the redirect idk
  restapi/solid.ts
Labels: heroku 🤺, docker 🐳

#171 Mario misc 170 move routers
  restapi/package-lock.json
  restapi/package.json
  restapi/routers/api.ts
  restapi/routers/solid.ts
  restapi/routers/solidEnsurer.ts
  restapi/server.ts
Labels: backend 💾

#169 Now solid should work with any number of users
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/solid.ts
  restapi/solidEnsurer.ts
Labels: solid 🪨, backend 💾

#172 Now /solid/address returns an array with all the addresses of a user, if any
  restapi/SOLID/API.ts
  restapi/routers/solid.ts
  webapp/src/api/api.ts
Labels: enhancement, solid 🪨, backend 💾
