Repository Arquisoft/dede_en3b, pull requests merged in 2022-05, with the labels that each got.

#235 Done tests to improve the coverage percentage.
  restapi/model/Order.ts
  restapi/routers/api.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/test.server.ts
  restapi/util/utils.ts
  webapp/jest.config.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/AddAddressComponent.tsx
  webapp/src/components/AddPaymentMeanComponent.tsx
  webapp/src/components/ConfirmationComponent.tsx
  webapp/src/components/NavigationBar.tsx
  webapp/src/components/Product.tsx
  webapp/src/components/reviews/ProductReviewList.tsx
  webapp/src/routes/Catalogue.tsx
  webapp/src/tests/AddressForm.test.tsx
  webapp/src/tests/Api.test.ts
  webapp/src/tests/CartItem.test.tsx
  webapp/src/tests/Catalogue.test.tsx
  webapp/src/tests/Checkout.test.tsx
  webapp/src/tests/IndividualOrder.test.tsx
  webapp/src/tests/IndividualOrderProduct.test.tsx
  webapp/src/tests/IndividualProduct.test.tsx
  webapp/src/tests/NavigationBar.test.tsx
  webapp/src/tests/OrderItem.test.tsx
  webapp/src/tests/PaymentForm.test.tsx
  webapp/src/tests/ProductComponent.test.tsx
  webapp/src/tests/ProductReview.test.tsx
  webapp/src/tests/ProductReviewList.test.tsx
  webapp/src/tests/Review.test.tsx
  webapp/src/tests/ShippingApi.test.ts
  webapp/src/tests/ShoppingCart.test.tsx
  webapp/src/tests/reportWebVitals.test.ts
  webapp/src/tests/utils.test.tsx
Labels: test 🧪

#242 Some changes to documentation
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/09_design_decisions.adoc
  docs/images/03-01_Mario_BusinessContext.png
  docs/images/03-02_Mario_TechnicalContext.png
Labels: documentation, enhancement

#243 maybe fix for session not storing?
  restapi/routers/solid.ts
  restapi/server.ts
Labels: documentation, enhancement

#244 Mario fix 163 solid handle more than one user
  restapi/routers/solid.ts
  restapi/server.ts
  webapp/src/api/api.ts
  webapp/src/components/checkout/Checkout.tsx
Labels: enhancement

#253 Forgot to install package
  restapi/package-lock.json
  restapi/package.json
Labels: documentation, enhancement

#255 Changed a couple of things, pray that this works
  restapi/server.ts
  webapp/src/api/api.ts
Labels: documentation, enhancement

#261 Mario fix 163 solid handle more than one user
  restapi/server.ts
Labels: enhancement

#262 sameSite false????
  restapi/server.ts
Labels: enhancement

#263 Changed cors origin back
  restapi/server.ts
Labels: documentation, enhancement

#264 Changed more things
  restapi/server.ts
Labels: documentation, enhancement

#265 Back to lax
  restapi/server.ts
Labels: documentation, enhancement

#267 Back to the origins
  restapi/routers/solid.ts
  restapi/server.ts
  webapp/src/api/api.ts
Labels: documentation, enhancement

#273 Maybe this works?
  restapi/server.ts
Labels: documentation, enhancement

#274 Forgot to change frontend api
  restapi/server.ts
Labels: documentation, enhancement

#276 Changed allow-headers router
  restapi/routers/solid.ts
  restapi/server.ts
Labels: documentation, enhancement

#277 Changed endpoints to new domain
  restapi/routers/solid.ts
  restapi/server.ts
  webapp/src/api/api.ts
Labels: documentation, enhancement
